export const EVENT_NOTE_ADDED = 'EVENT_NOTE_ADDED';
export const EVENT_NOTE_PINNED = 'EVENT_NOTE_PINNED';
export const EVENT_NOTE_MARKED = 'EVENT_NOTE_MARKED';
export const EVENT_NOTE_CLONED = 'EVENT_NOTE_CLONED';
export const EVENT_NOTE_DELETED = 'EVENT_NOTE_DELETED';

export const EVENT_EMAIL_SAVED = 'EVENT_EMAIL_SAVED';
export const EVENT_EMAIL_DELETED = 'EVENT_EMAIL_DELETED';

export const eventBus = new Vue();
