export const EVENT_NOTE_SAVED = 'EVENT_NOTE_SAVED';
export const EVENT_NOTE_PINNED = 'EVENT_NOTE_PINNED';
export const EVENT_NOTE_DELETED = 'EVENT_NOTE_DELETED';

export const EVENT_EMAIL_SAVED = 'EVENT_EMAIL_SAVED';
export const EVENT_EMAIL_DELETED = 'EVENT_EMAIL_DELETED';

export const eventBus = new Vue();
